print("***Bienvenido, vamos a validar como funciona una aplicación de control de versiones ***")
print("***A continuación podra comprobar el resultado de diversas operaciones matematicas  ***")
print(6 // 3)
print(6 // 3.)
print(6. // 3)
print(6. // 3.)
